### ISSUE TITLE
Unite sdmx-js and sdmx-typescript on npm

### ISSUE THREAD

**Issue by Isaac-Leonard** [kalessine/sdmx-js#3]
Currently there appears to be two seperate versions of this repo on npm but the typescript one links to a dead repo which I assume is meant to be this one.
It would probably be good to update the repo links for it to point to this or pull it off npm completely so there's only the one package.

**Comment by Isaac-Leonard** [comment]
That would be very helpful thank you
I checked out the sdmx-vue repo and it looks like the ddmx module is exactly what I want.
I'm working on building an centralised api to work with various organisations SDMX apis and it looks as though you've already done a large chunk of that, do you mind if I clone it and use it for my own purposes with attribution given to you?

**Comment by kalessine** [comment]
Sure! Go for it! Glad to hear it will be useful :)Sent from my Galaxy
-------- Original message --------From: Isaac-Leonard ***@***.***> Date: 15/10/21  1:16 pm  (GMT+08:00) To: kalessine/sdmx-js ***@***.***> Cc: kalessine ***@***.***>, Comment ***@***.***> Subject: Re: [kalessine/sdmx-js] Unite sdmx-js and sdmx-typescript on npm (#3) 
That would be very helpful thank you
I checked out the sdmx-vue repo and it looks like the ddmx module is exactly what I want.
I'm working on building an centralised api to work with various organisations SDMX apis and it looks as though you've already done a large chunk of that, do you mind if I clone it and use it for my own purposes with attribution given to you?
